name: Build StreamUP Library
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v2
 
    - name: Build Library
      run: msbuild "StreamUP DLL.sln" -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Extract Version Number
      id: version
      run: |
        $version = [System.IO.File]::ReadAllText("${{ github.workspace }}\StreamUP DLL\Properties\AssemblyInfo.cs") -match 'AssemblyVersion\("([^"]+)"\)' | Out-Null
        $versionNumber = $matches[1]
        echo "Extracted version: $versionNumber"
        echo "::set-output name=VERSION::$versionNumber"

    - name: Upload Library Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StreamUP Library
        path: ${{ github.workspace }}\StreamUP DLL\bin\Release\StreamUP.dll

    - name: Release Library
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        files: |
          ${{ github.workspace }}\StreamUP DLL\bin\Release\StreamUP.dll
